<?php

namespace ContainerJNT8dMJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplyPenaltyCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ApplyPenaltyCommand' shared autowired service.
     *
     * @return \App\Command\ApplyPenaltyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ApplyPenaltyCommand.php';

        $container->privates['App\\Command\\ApplyPenaltyCommand'] = $instance = new \App\Command\ApplyPenaltyCommand(($container->privates['App\\Repository\\ParcelRepository'] ?? $container->load('getParcelRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService')));

        $instance->setName('app:apply-penalty');
        $instance->setDescription('Apply penalty fees to parcels not collected within 10 days');

        return $instance;
    }
}
