<?php

namespace ContainerJNT8dMJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplyPenaltyCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ApplyPenaltyCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ApplyPenaltyCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:apply-penalty', [], 'Apply penalty fees to parcels not collected within 10 days', false, #[\Closure(name: 'App\\Command\\ApplyPenaltyCommand')] fn (): \App\Command\ApplyPenaltyCommand => ($container->privates['App\\Command\\ApplyPenaltyCommand'] ?? $container->load('getApplyPenaltyCommandService')));
    }
}
