<?php

namespace ContainerJNT8dMJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateManagerCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateManagerCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateManagerCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-manager', [], 'Creates a new manager user', false, #[\Closure(name: 'App\\Command\\CreateManagerCommand')] fn (): \App\Command\CreateManagerCommand => ($container->privates['App\\Command\\CreateManagerCommand'] ?? $container->load('getCreateManagerCommandService')));
    }
}
