<?php

namespace ContainerJNT8dMJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParcelTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ParcelType' shared autowired service.
     *
     * @return \App\Form\ParcelType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ParcelType.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CountryService.php';

        return $container->privates['App\\Form\\ParcelType'] = new \App\Form\ParcelType(new \App\Service\CountryService());
    }
}
