<?php

namespace ContainerCmUY9mk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HpLUjt_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HpLUjt.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HpLUjt.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ParcelController::applyPenalty' => ['privates', '.service_locator.G65vspt', 'get_ServiceLocator_G65vsptService', true],
            'App\\Controller\\ParcelController::show' => ['privates', '.service_locator.tA1K03X', 'get_ServiceLocator_TA1K03XService', true],
            'App\\Controller\\ParcelController::updateStatus' => ['privates', '.service_locator.G65vspt', 'get_ServiceLocator_G65vsptService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\StatisticsController::apiStatistics' => ['privates', '.service_locator.tA1K03X', 'get_ServiceLocator_TA1K03XService', true],
            'App\\Controller\\StatisticsController::index' => ['privates', '.service_locator.tA1K03X', 'get_ServiceLocator_TA1K03XService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ParcelController:applyPenalty' => ['privates', '.service_locator.G65vspt', 'get_ServiceLocator_G65vsptService', true],
            'App\\Controller\\ParcelController:show' => ['privates', '.service_locator.tA1K03X', 'get_ServiceLocator_TA1K03XService', true],
            'App\\Controller\\ParcelController:updateStatus' => ['privates', '.service_locator.G65vspt', 'get_ServiceLocator_G65vsptService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\StatisticsController:apiStatistics' => ['privates', '.service_locator.tA1K03X', 'get_ServiceLocator_TA1K03XService', true],
            'App\\Controller\\StatisticsController:index' => ['privates', '.service_locator.tA1K03X', 'get_ServiceLocator_TA1K03XService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ParcelController::applyPenalty' => '?',
            'App\\Controller\\ParcelController::show' => '?',
            'App\\Controller\\ParcelController::updateStatus' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\StatisticsController::apiStatistics' => '?',
            'App\\Controller\\StatisticsController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ParcelController:applyPenalty' => '?',
            'App\\Controller\\ParcelController:show' => '?',
            'App\\Controller\\ParcelController:updateStatus' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\StatisticsController:apiStatistics' => '?',
            'App\\Controller\\StatisticsController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
