<?php

namespace ContainerCmUY9mk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G65vsptService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G65vspt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G65vspt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'parcel' => ['privates', '.errored..service_locator.G65vspt.App\\Entity\\Parcel', NULL, 'Cannot autowire service ".service_locator.G65vspt": it needs an instance of "App\\Entity\\Parcel" but this type has been excluded in "config/services.yaml".'],
        ], [
            'parcel' => 'App\\Entity\\Parcel',
        ]);
    }
}
