<?php

namespace ContainerCmUY9mk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TA1K03XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tA1K03X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tA1K03X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'parcelRepository' => ['privates', 'App\\Repository\\ParcelRepository', 'getParcelRepositoryService', true],
        ], [
            'parcelRepository' => 'App\\Repository\\ParcelRepository',
        ]);
    }
}
