<?php

namespace ContainerCmUY9mk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateManagerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateManagerCommand' shared autowired service.
     *
     * @return \App\Command\CreateManagerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateManagerCommand.php';

        $container->privates['App\\Command\\CreateManagerCommand'] = $instance = new \App\Command\CreateManagerCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:create-manager');
        $instance->setDescription('Creates a new manager user');

        return $instance;
    }
}
