<?php

namespace ContainerCmUY9mk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParcelControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ParcelController' shared autowired service.
     *
     * @return \App\Controller\ParcelController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ParcelController.php';

        $container->services['App\\Controller\\ParcelController'] = $instance = new \App\Controller\ParcelController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService')), ($container->privates['App\\Repository\\ParcelRepository'] ?? $container->load('getParcelRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ParcelController', $container));

        return $instance;
    }
}
