<?php

namespace ContainerCmUY9mk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParcelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.G65vspt.App\Entity\Parcel' shared service.
     *
     * @return \App\Entity\Parcel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.G65vspt": it needs an instance of "App\\Entity\\Parcel" but this type has been excluded in "config/services.yaml".');
    }
}
