<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJNT8dMJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJNT8dMJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJNT8dMJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJNT8dMJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJNT8dMJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'JNT8dMJ',
    'container.build_id' => '78a249aa',
    'container.build_time' => 1749077274,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJNT8dMJ');
