<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_parcel_new' => [[], ['_controller' => 'App\\Controller\\ParcelController::new'], [], [['text', '/parcel/new']], [], [], []],
    'app_parcel_show' => [['trackingNumber'], ['_controller' => 'App\\Controller\\ParcelController::show'], [], [['variable', '/', '[^/]++', 'trackingNumber', true], ['text', '/parcel/track']], [], [], []],
    'app_parcel_list' => [[], ['_controller' => 'App\\Controller\\ParcelController::list'], [], [['text', '/parcel/list']], [], [], []],
    'app_parcel_update_status' => [['id'], ['_controller' => 'App\\Controller\\ParcelController::updateStatus'], [], [['text', '/update-status'], ['variable', '/', '[^/]++', 'id', true], ['text', '/parcel']], [], [], []],
    'app_parcel_apply_penalty' => [['id'], ['_controller' => 'App\\Controller\\ParcelController::applyPenalty'], [], [['text', '/apply-penalty'], ['variable', '/', '[^/]++', 'id', true], ['text', '/parcel']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_statistics' => [[], ['_controller' => 'App\\Controller\\StatisticsController::index'], [], [['text', '/admin/statistics']], [], [], []],
    'app_statistics_api' => [[], ['_controller' => 'App\\Controller\\StatisticsController::apiStatistics'], [], [['text', '/admin/statistics/api']], [], [], []],
];
